apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-ruler-custom-rules
  namespace: open-cluster-management-observability
  labels:
    faro.io/rule-configmap: "true"
data:
  custom_rules.yaml: | # <--- This pipe is for the ConfigMap data
    groups:
      - name: bookinfo-global-rules
        rules:
          - alert: ReviewsServiceFailure
            # Use the pipe | here for the expression itself
            expr: |
              kube_deployment_status_replicas_available{cluster="cluster1",deployment="reviews-v1",namespace="bookinfo"} == 0  
            for: 30s
            labels:
              severity: critical
              action: migrate
            annotations:
              summary: "Reviews service is down on {{ $labels.cluster }}"

      - name: eda-test.rules
        rules:
          - alert: DummyAlertTriggered
            expr: absent(kube_configmap_info{configmap="eda-trigger-map", namespace="default"}) == 1
            for: 1m
            labels:
              severity: critical
              cluster: cluster1
              action: resistere
            annotations:
              summary: "EDA Trigger Map is missing on cluster1"
              description: "This alert is used to test the ACM to EDA integration."