---
- name: Fix Cluster1 Issues
  hosts: localhost
  connection: local
  tasks:
    - name: Log the incoming alert
      ansible.builtin.debug:
        msg: "Received FIRING alert '{{ alert_summary }}' from cluster '{{ target_cluster }}'"

    - name: Remediate Missing ConfigMap
      kubernetes.core.k8s:
        #host: https://api.cluster1.sandbox690.opentlc.com:6443
        #validate_certs: false
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: eda-trigger-map
            namespace: default
          data:
            status: "remediated-by-ansible"
            timestamp: "{{ ansible_date_time.iso8601 }}"
      when: target_cluster == "cluster1"

    - name: Notification of success
      ansible.builtin.debug:
        msg: "Remediation complete for {{ target_cluster }}."