---
- name: Create Namespace on ACM Managed Cluster
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vault/vault.yaml  # Contains hub_url and token_acm
  vars:
    target_cluster: "local-cluster"
    namespace_name: "prod-apps"

  tasks:
    - name: Verify API connectivity
      ansible.builtin.command:
        cmd: printenv | grep K8S_AUTH
      register: env_check
      ignore_errors: true

    - name: Show injected variables
      ansible.builtin.debug:
        var: env_check.stdout_lines

    - name: Create ManifestWork on Hub to deploy Namespace to Spoke
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: work.open-cluster-management.io/v1
          kind: ManifestWork
          metadata:
            name: "create-{{ namespace_name }}-ns"
            # In ACM, ManifestWorks must be in the namespace named after the cluster
            namespace: "{{ target_cluster }}"
          spec:
            workload:
              manifests:
                - apiVersion: v1
                  kind: Namespace
                  metadata:
                    name: "{{ namespace_name }}"
                    labels:
                      managed-by: "acm-aap-integration"